[project]
name = "aiventura"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [{name = "Didac Fortuny", email = "dacfortuny@gmail.com"}]
requires-python = "<4.0,>=3.11"
dependencies = [
    "omegaconf",
    "langchain",
    "langchain-mistralai",
]

[tool.uv]
dev-dependencies = [
    "jupyterlab",
    "isort",
    "jupytext",
    "pytest"
]